from typing import TypedDict, Any


class AnalysisState(TypedDict, total=False):
    # --- Identity (set at invocation) ---
    run_id: str                    # UUID of the RunRow in SQLite
    session_id: str                # UUID of the SessionRow; used to look up uploaded tables
    question: str                  # verbatim natural-language question from the user

    # --- Skeleton compat (always present) ---
    input_text: str                # alias for question (backward compat with RunRow)
    output_text: str               # alias for insight_text (written by generate_insights, read by finalize)
    error: str | None              # set by any node on fatal failure; None on success
    messages: list                 # unused in this agent; kept for skeleton compat

    # --- Intermediate: generate_sql ---
    uploaded_tables: list[str]     # table names available in this session
    schema_context: str            # serialized schema + sample rows sent to Gemini
    sql_query: str                 # SQL SELECT generated by Gemini and validated

    # --- Intermediate: execute_sql ---
    query_rows: list[dict[str, Any]]  # rows returned by SQL execution; max 10 000
    rows_truncated: bool           # True if result was capped at 10 000

    # --- Output: generate_insights ---
    insight_json: dict[str, Any]   # structured statistics from Python computation
    insight_text: str              # prose narrative from Gemini

    # --- Output: generate_charts ---
    chart_specs: list[dict[str, Any]]  # ChartSpec list; up to 4 entries


# Keep AgentState as an alias for backward compatibility with existing tests
AgentState = AnalysisState
