"""add_message_tokens

Revision ID: 84404809a3d8
Revises: 3b86e87fef32
Create Date: 2026-06-18 17:36:30.658864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84404809a3d8'
down_revision: Union[str, None] = '3b86e87fef32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tokens_input', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('tokens_output', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tokens_output')
    op.drop_column('messages', 'tokens_input')
    # ### end Alembic commands ###
