"""add chart_json to messages

Revision ID: a5ff0c00d8cb
Revises: 3c3baf965a3b
Create Date: 2026-06-19 01:44:23.472472

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a5ff0c00d8cb'
down_revision: Union[str, None] = '3c3baf965a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('chart_json')

    # ### end Alembic commands ###
