"""API tests for the MCP-server model: upload→create (auto-sync), duplicate rejection, external 501,
MCP JSON-RPC dispatch (tools/list+call, errors), sync version bump (soft-delete), and delete — all in
stub mode against a tmp SQLite DB."""
import csv
import io
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import data_analysis_agent.db.session as session_module
from data_analysis_agent.db.database import Database
from data_analysis_agent.db.models import DatabaseRow, McpResourceRow, McpToolRow


@pytest.fixture(autouse=True)
def _env(tmp_path, monkeypatch):
    monkeypatch.setenv("DATAANALYSIS_OPENROUTER_API_KEY", "")
    monkeypatch.setenv("DATAANALYSIS_UPLOAD_DIR", str(tmp_path / "uploads"))
    monkeypatch.setenv("DATAANALYSIS_DATASETS_DIR", str(tmp_path / "datasets"))
    monkeypatch.setenv("DATAANALYSIS_CHECKPOINT_DB", str(tmp_path / "ckpt.db"))
    db = Database(f"sqlite:///{tmp_path / 'app.db'}")
    db._init_schema()
    monkeypatch.setattr(session_module, "_db", db)
    monkeypatch.setattr(session_module, "init_db", lambda: None)
    yield
    db._dispose()
    monkeypatch.setattr(session_module, "_db", None)


@pytest.fixture
def client():
    import data_analysis_agent.llm.client as llm_module
    llm_module._client = None
    from data_analysis_agent.api import create_app
    with TestClient(create_app(), raise_server_exceptions=True) as c:
        yield c


def _csv(*rows) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    for r in rows:
        w.writerow(r)
    return buf.getvalue().encode()


def _orders() -> bytes:
    return _csv(["id", "amount"], [1, 5], [2, 7])


def _create(client, name: str, data: bytes | None = None, filename: str = "orders.csv"):
    up = client.post("/database/upload", data={"database_name": name},
                     files={"file": (filename, data or _orders(), "text/csv")})
    assert up.status_code == 200, up.text
    uri = up.json()["uri"]
    return client.post("/database", data={"name": name, "database_type": "parquet", "database_uri": uri},
                       follow_redirects=True)


def _table_count(db, database_id: str) -> int:
    """Active entity (non-schema) resources = the database's tables (no stored physical catalog)."""
    return (
        db.query(McpResourceRow)
        .filter(McpResourceRow.database_id == database_id, McpResourceRow.deleted_at.is_(None),
                McpResourceRow.kind != "schema")
        .count()
    )


def _only_server():
    with session_module.create_db_session() as db:
        srv = db.query(DatabaseRow).one()
        return srv.id, srv.version, _table_count(db, srv.id)


def test_create_builds_server_and_capabilities(client):
    r = _create(client, "Sales DB")
    assert r.status_code == 200
    with session_module.create_db_session() as db:
        srv = db.query(DatabaseRow).one()
        assert srv.name == "Sales DB" and srv.type == "parquet"
        assert srv.uri == "parquet:///Sales%20DB"
        assert srv.title and srv.description           # generated by the sync stub
        assert srv.version >= 2                         # create(1) + sync apply bumps to 2
        assert _table_count(db, srv.id) == 1            # one entity resource per inspected table
        tools = db.query(McpToolRow).filter_by(database_id=srv.id, deleted_at=None).all()
        assert len(tools) >= 1


def test_duplicate_name_rejected(client):
    _create(client, "Dupe")
    up = client.post("/database/upload", data={"database_name": "Dupe"},
                     files={"file": ("b.csv", _orders(), "text/csv")})
    uri = up.json()["uri"]
    r = client.post("/database", data={"name": "Dupe", "database_type": "parquet", "database_uri": uri},
                    follow_redirects=False)
    assert r.status_code == 400


def test_create_without_upload_succeeds_with_zero_tables(client):
    # A parquet database may contain zero tables (nothing uploaded yet) — that is valid.
    r = client.post("/database",
                    data={"name": "Empty", "database_type": "parquet", "database_uri": "parquet:///Empty"},
                    follow_redirects=True)
    assert r.status_code == 200
    _, _, n_tables = _only_server()
    assert n_tables == 0


def test_jsonrpc_tools_list_call_and_errors(client):
    _create(client, "RPC DB")
    database_id, _, _ = _only_server()

    listed = client.post(f"/database/{database_id}",
                         json={"jsonrpc": "2.0", "id": 1, "method": "tools/list"})
    assert listed.status_code == 200
    body = listed.json()
    tools = body["result"]["tools"]
    assert tools and "inputSchema" in tools[0]
    tool_name = tools[0]["name"]

    called = client.post(f"/database/{database_id}",
                         json={"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                               "params": {"name": tool_name, "arguments": {}}}).json()
    assert called["result"]["isError"] is False
    assert called["result"]["content"][0]["type"] == "text"

    # resources + prompts also list
    res = client.post(f"/database/{database_id}",
                      json={"jsonrpc": "2.0", "id": 3, "method": "resources/list"}).json()
    assert any(r["uri"].endswith("/schema") for r in res["result"]["resources"])

    # unknown method → -32601, unknown tool → -32602
    unk = client.post(f"/database/{database_id}",
                      json={"jsonrpc": "2.0", "id": 4, "method": "nope/x"}).json()
    assert unk["error"]["code"] == -32601
    bad = client.post(f"/database/{database_id}",
                      json={"jsonrpc": "2.0", "id": 5, "method": "tools/call",
                            "params": {"name": "does_not_exist", "arguments": {}}}).json()
    assert bad["error"]["code"] == -32602


def test_sync_bumps_version(client):
    _create(client, "SyncDB")
    database_id, v_before, _ = _only_server()
    r = client.post(f"/database/{database_id}/sync", follow_redirects=False)
    assert r.status_code == 303
    _, v_after, _ = _only_server()
    assert v_after == v_before + 1


def test_add_table_via_upload_then_sync(client):
    # Adding a table = the upload API reused + a sync (which re-inspects the directory).
    _create(client, "GrowDB")
    database_id, _, n_before = _only_server()
    up = client.post("/database/upload", data={"database_name": "GrowDB"},
                     files={"file": ("customers.csv", _csv(["id", "region"], [1, "N"]), "text/csv")})
    assert up.status_code == 200, up.text
    r = client.post(f"/database/{database_id}/sync", follow_redirects=False)
    assert r.status_code == 303
    _, _, n_after = _only_server()
    assert n_after == n_before + 1


def _rpc(client, database_id, method, params=None, rpc_id=1):
    body = {"jsonrpc": "2.0", "id": rpc_id, "method": method}
    if params is not None:
        body["params"] = params
    return client.post(f"/database/{database_id}", json=body).json()


_GOOD_TOOL = {"name": "recent_orders", "description": "Recent orders",
              "sql_template": "SELECT * FROM orders LIMIT 3",
              "input_schema": {"type": "object", "properties": {}}}


def test_tools_add_succeeds_and_cascades_prompts(client):
    _create(client, "MutDB")
    database_id, v_before, _ = _only_server()
    res = _rpc(client, database_id, "tools/add", {"definition": _GOOD_TOOL})["result"]
    assert res["ok"] is True and res["applied"]["key"] == "recent_orders"
    _, v_after, _ = _only_server()
    assert v_after == v_before + 1
    tools = _rpc(client, database_id, "tools/list")["result"]["tools"]
    assert any(t["name"] == "recent_orders" for t in tools)
    prompts = _rpc(client, database_id, "prompts/list")["result"]["prompts"]
    assert any(p["name"] == "explore_recent_orders" for p in prompts)   # additive cascade


def test_tools_add_duplicate_is_invalid_params(client):
    _create(client, "DupTool")
    database_id, _, _ = _only_server()
    _rpc(client, database_id, "tools/add", {"definition": _GOOD_TOOL})
    dup = _rpc(client, database_id, "tools/add", {"definition": _GOOD_TOOL})
    assert dup["error"]["code"] == -32602


def test_tools_add_bad_sql_is_invalid_params_and_not_persisted(client):
    _create(client, "BadSql")
    database_id, _, n0 = _only_server()
    before = len(_rpc(client, database_id, "tools/list")["result"]["tools"])
    bad = {"definition": {"name": "evil", "sql_template": "DELETE FROM orders",
                          "input_schema": {"type": "object", "properties": {}}}}
    resp = _rpc(client, database_id, "tools/add", bad)
    assert resp["error"]["code"] == -32602
    after = len(_rpc(client, database_id, "tools/list")["result"]["tools"])
    assert after == before                                              # nothing persisted


def test_prompts_add_succeeds(client):
    _create(client, "PromptDB")
    database_id, _, _ = _only_server()
    res = _rpc(client, database_id, "prompts/add",
               {"definition": {"name": "my_prompt", "description": "mine"}})["result"]
    assert res["ok"] is True
    prompts = _rpc(client, database_id, "prompts/list")["result"]["prompts"]
    assert any(p["name"] == "my_prompt" for p in prompts)


def test_unknown_method_is_method_not_found(client):
    _create(client, "NoMethod")
    database_id, _, _ = _only_server()
    resp = _rpc(client, database_id, "tools/rename", {"definition": {"name": "x"}})
    assert resp["error"]["code"] == -32601                             # not a real method → -32601


def test_tools_delete_hard_deletes_and_prunes_prompts(client):
    _create(client, "DelTool")
    database_id, v_before, _ = _only_server()
    _rpc(client, database_id, "tools/add", {"definition": _GOOD_TOOL})
    assert any(p["name"] == "explore_recent_orders"
               for p in _rpc(client, database_id, "prompts/list")["result"]["prompts"])
    res = _rpc(client, database_id, "tools/delete", {"name": "recent_orders"})["result"]
    assert res["ok"] is True and res["applied"]["op"] == "delete"
    tools = {t["name"] for t in _rpc(client, database_id, "tools/list")["result"]["tools"]}
    assert "recent_orders" not in tools                                # gone (hard delete)
    prompts = {p["name"] for p in _rpc(client, database_id, "prompts/list")["result"]["prompts"]}
    assert "explore_recent_orders" not in prompts                      # pruned by the cascade


def test_resources_delete_drops_table(client):
    _create(client, "DelRes")
    database_id, _, _ = _only_server()
    resources = _rpc(client, database_id, "resources/list")["result"]["resources"]
    entity = next(r for r in resources if not r["uri"].endswith("/schema"))
    res = _rpc(client, database_id, "resources/delete", {"uri": entity["uri"]})["result"]
    assert res["ok"] is True
    with session_module.create_db_session() as db:
        assert _table_count(db, database_id) == 0                      # backing table dropped + re-inspected


def test_resources_delete_schema_is_rejected(client):
    _create(client, "KeepSchema")
    database_id, _, _ = _only_server()
    resources = _rpc(client, database_id, "resources/list")["result"]["resources"]
    schema = next(r for r in resources if r["uri"].endswith("/schema"))
    resp = _rpc(client, database_id, "resources/delete", {"uri": schema["uri"]})
    assert resp["error"]["code"] == -32602                            # schema resource is undeletable


def test_delete_removes_dir_and_rows(client):
    from data_analysis_agent.config.settings import get_settings
    from data_analysis_agent.tools.table_naming import sql_table_name
    _create(client, "ToDelete")
    database_id, _, _ = _only_server()
    dataset_dir = Path(get_settings().datasets_dir) / sql_table_name("ToDelete")
    assert dataset_dir.exists()

    r = client.post(f"/database/{database_id}/delete", follow_redirects=True)
    assert r.status_code == 200
    with session_module.create_db_session() as db:
        assert db.query(DatabaseRow).count() == 0
        assert db.query(McpToolRow).count() == 0
    assert not dataset_dir.exists()
