import json
from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Float, Index, Integer, Text, TIMESTAMP, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _uuid() -> str:
    """Return a new random UUID string for use as a primary-key default."""
    return str(uuid4())


def _now() -> datetime:
    """Return the current time as a timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


def _loads(raw: str | None, default):
    """Decode JSON ``raw`` or return ``default`` when unset."""
    return json.loads(raw) if raw else default


def input_schema_from_parameters(parameters: list[dict]) -> dict:
    """Derive an MCP ``inputSchema`` object from a tool's execution ``parameters`` list.

    Each parameter is ``{"name", "type", "description?", "required?"}``; the derived schema is the
    standard ``{"type": "object", "properties": {...}, "required": [...]}`` MCP clients expect.
    """
    props: dict = {}
    required: list[str] = []
    for p in parameters or []:
        name = p.get("name")
        if not name:
            continue
        prop: dict = {"type": p.get("type") or "string"}
        if p.get("description"):
            prop["description"] = p["description"]
        props[name] = prop
        if p.get("required"):
            required.append(name)
    schema: dict = {"type": "object", "properties": props}
    if required:
        schema["required"] = required
    return schema


class Base(DeclarativeBase):
    pass


class DatabaseRow(Base):
    """A **database** — an instance of an MCP server *type* (``type``: parquet, postgresql, …), backed
    1:1 by a dataset URI. Each type's connector logic + behaviour lives in code (``tools/connectors/``).

    Per the MCP spec a database (served as an MCP server) has three kinds of children — tools, resources,
    prompts — generated by the sync pipeline and stored as rows. The dataset itself is not a separate
    entity: only its URI + type are metadata on this row; its **physical tables are inspected live by
    the connector** (no stored catalog). The dataset's per-table columns live on the entity resources and
    its entity-relationship schema on the ``kind='schema'`` resource (the source of truth). ``name`` and
    ``uri`` are unique (the 1:1 dataset↔database constraint).
    """

    __tablename__ = "databases"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    type: Mapped[str] = mapped_column(Text, nullable=False, default="parquet")  # MCP server type
    uri: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    last_synced_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    last_sync_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    connection_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )


class _CapabilityMixin:
    """Shared versioning + soft-delete envelope for tool/resource/prompt child rows.

    Capabilities are NEVER hard-deleted by sync or the dispatcher: a removal sets ``deleted_at`` +
    ``deleted_version``. The "active" view is ``database_id = ? AND deleted_at IS NULL``.
    """

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    database_id: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    created_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    deleted_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    deleted_version: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class McpToolRow(_CapabilityMixin, Base):
    """A canned "GET-API" MCP tool: a parameterized read-only SELECT over the server's tables.

    The tool's execution spec is a single JSON object column, ``execution_json``::

        {"sql_template": "SELECT … WHERE x > $min",
         "parameters": [{"name": "min", "type": "integer", "description": "…", "required": true}]}

    ``sql_template`` carries the ``$param`` embeddings; ``parameters`` defines each embedding's name +
    type. This object is the **source of truth for the executor**. The MCP-advertised ``inputSchema`` and
    the bare ``sql_template`` are *derived* from it (read-only properties) — there is no separate column.
    """

    __tablename__ = "mcp_tools"
    __table_args__ = (
        Index(
            "uq_mcp_tools_active_name",
            "database_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
    )

    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    execution_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    output_schema_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    annotations_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    @property
    def execution(self) -> dict:
        """The executor spec: ``{"sql_template": str, "parameters": [{"name","type",...}]}``."""
        return _loads(self.execution_json, {})

    @execution.setter
    def execution(self, value: dict) -> None:
        self.execution_json = json.dumps(value or {})

    @property
    def parameters(self) -> list[dict]:
        """The declared ``$param`` embeddings: ``[{"name","type","description?","required?"}]``."""
        return (self.execution or {}).get("parameters") or []

    @property
    def sql_template(self) -> str:
        """The SQL template (with ``$param`` embeddings), derived from ``execution``."""
        return (self.execution or {}).get("sql_template") or ""

    @property
    def input_schema(self) -> dict:
        """MCP ``inputSchema`` derived from the execution parameter specs."""
        return input_schema_from_parameters(self.parameters)

    @property
    def output_schema(self) -> dict | None:
        return _loads(self.output_schema_json, None)

    @property
    def annotations(self) -> dict | None:
        return _loads(self.annotations_json, None)


class McpResourceRow(_CapabilityMixin, Base):
    """An MCP resource: the dataset schema, or a primary/secondary entity derived from it."""

    __tablename__ = "mcp_resources"
    __table_args__ = (
        # A resource URI is unique at the DB level (among active rows — soft-deleted tombstones are
        # excluded so a pruned entity can be re-added under the same URI).
        Index(
            "uq_mcp_resources_active_uri",
            "uri",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
    )

    uri: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    mime_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    kind: Mapped[str] = mapped_column(Text, nullable=False, default="primary_entity")
    content_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    size: Mapped[int | None] = mapped_column(Integer, nullable=True)  # bytes: parquet file (table) or content_json (schema)

    @property
    def content(self):
        return _loads(self.content_json, None)

    @content.setter
    def content(self, value) -> None:
        self.content_json = json.dumps(value)


class McpPromptRow(_CapabilityMixin, Base):
    """An MCP prompt template over the server's tools."""

    __tablename__ = "mcp_prompts"
    __table_args__ = (
        Index(
            "uq_mcp_prompts_active_name",
            "database_id",
            "name",
            unique=True,
            sqlite_where=text("deleted_at IS NULL"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
    )

    name: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    arguments_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    template_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    @property
    def arguments(self) -> list[dict]:
        return _loads(self.arguments_json, [])

    @property
    def template(self):
        return _loads(self.template_json, None)


class SessionRow(Base):
    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    name: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class SessionDatabaseRow(Base):
    """Join table linking a session to the MCP servers it spans (many-to-many)."""

    __tablename__ = "session_databases"

    session_id: Mapped[str] = mapped_column(Text, primary_key=True)
    database_id: Mapped[str] = mapped_column(Text, primary_key=True)


class QueryRecordRow(Base):
    __tablename__ = "query_records"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    session_id: Mapped[str] = mapped_column(Text, nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    iteration_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    query_history_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    total_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    api_request_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )

    @property
    def query_history(self) -> list[dict]:
        """Decode the tool-call trace: [{tool, arguments, result, is_error, capability?}]."""
        return _loads(self.query_history_json, [])


class AgentRunRow(Base):
    __tablename__ = "agent_runs"

    id: Mapped[str] = mapped_column(Text, primary_key=True, default=_uuid)
    query_record_id: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=_now, onupdate=_now
    )
